<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="LPMB-KOl-Sahelee.local" name="com.fusioncharts.apitest.StartingAngle" tests="4" failures="0" timestamp="21 Aug 2019 11:09:30 GMT" time="6.336" errors="1">
  <testcase name="setUp" time="6.336" classname="com.fusioncharts.apitest.StartingAngle">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.fusioncharts.util.TestUtil.getTestData(TestUtil.java:44)
at com.fusioncharts.apitest.StartingAngle.setUp(StartingAngle.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="verifyAPIExistsInDataSheetStartingAngle" time="0.000" classname="com.fusioncharts.apitest.StartingAngle">
    <skipped/>
  </testcase> <!-- verifyAPIExistsInDataSheetStartingAngle -->
  <testcase name="verifyChartIsRenderedStartingAngle" time="0.000" classname="com.fusioncharts.apitest.StartingAngle">
    <skipped/>
  </testcase> <!-- verifyChartIsRenderedStartingAngle -->
  <testcase name="verifyAPIStartingAngle" time="0.000" classname="com.fusioncharts.apitest.StartingAngle">
    <skipped/>
  </testcase> <!-- verifyAPIStartingAngle -->
</testsuite> <!-- com.fusioncharts.apitest.StartingAngle -->
