<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LPMB-Kol-Saurav.local" name="com.fusioncharts.apitest.AnnotationAPIs" tests="3" failures="1" timestamp="24 Sep 2019 12:53:05 GMT" time="66.387" errors="0">
  <testcase name="verifyAPIExistsInDataSheetAnnotationAPIs" time="0.001" classname="com.fusioncharts.apitest.AnnotationAPIs"/>
  <testcase name="verifyChartIsRenderedAnnotationAPIs" time="0.898" classname="com.fusioncharts.apitest.AnnotationAPIs"/>
  <testcase name="verifyAPIAnnotationAPIs" time="65.488" classname="com.fusioncharts.apitest.AnnotationAPIs">
    <failure type="java.lang.AssertionError" message="Marker Updated screenshot matches correctly expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Marker Updated screenshot matches correctly expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.fusioncharts.apitest.AnnotationAPIs.verifyAPIAnnotationAPIs(AnnotationAPIs.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAPIAnnotationAPIs -->
</testsuite> <!-- com.fusioncharts.apitest.AnnotationAPIs -->
